### ISSUE TITLE
I can't download the package inside the Atom UI

### ISSUE THREAD

**Issue by aliparlakci** [Sorunome/arduino-upload#18] opened 2017-04-10 19:48 UTC
This is the error code I get:

 serialport@4.0.7 install C:\Users\Ali\AppData\Local\Temp\apm-install-dir-117310-7644-1i0dxte\node_modules\arduino-upload\node_modules\serialport
 node-pre-gyp install --fallback-to-build

Failed to execute 'C:\Users\Ali\AppData\Local\atom\app-1.15.0\resources\app\apm\bin\node.exe C:\Users\Ali\AppData\Local\atom\app-1.15.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Ali\AppData\Local\Temp\apm-install-dir-117310-7644-1i0dxte\node_modules\arduino-upload\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\Ali\AppData\Local\Temp\apm-install-dir-117310-7644-1i0dxte\node_modules\arduino-upload\node_modules\serialport\build\Release' (1)
C:\Users\Ali\AppData\Local\Temp\apm-install-dir-117310-7644-1i0dxte
`-- (empty)

node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-electron-v1.3-win32-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and electron@1.3.13 (electron-v1.3 ABI) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Ali\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\Ali\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\Ali\AppData\Local\atom\app-1.15.0\resources\app\apm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\Ali\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Ali\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Ali\\AppData\\Local\\Temp\\apm-install-dir-117310-7644-1i0dxte\\node_modules\\arduino-upload\\node_modules\\serialport\\build\\Release\\serialport.node" "--module_name=serialport" "--module_path=C:\\Users\\Ali\\AppData\\Local\\Temp\\apm-install-dir-117310-7644-1i0dxte\\node_modules\\arduino-upload\\node_modules\\serialport\\build\\Release"
gyp ERR! cwd C:\Users\Ali\AppData\Local\Temp\apm-install-dir-117310-7644-1i0dxte\node_modules\arduino-upload\node_modules\serialport
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\Ali\AppData\Local\atom\app-1.15.0\resources\app\apm\bin\node.exe C:\Users\Ali\AppData\Local\atom\app-1.15.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Ali\AppData\Local\Temp\apm-install-dir-117310-7644-1i0dxte\node_modules\arduino-upload\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\Ali\AppData\Local\Temp\apm-install-dir-117310-7644-1i0dxte\node_modules\arduino-upload\node_modules\serialport\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Ali\AppData\Local\Temp\apm-install-dir-117310-7644-1i0dxte\node_modules\arduino-upload\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Users\\Ali\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Ali\\AppData\\Local\\Temp\\apm-install-dir-117310-7644-1i0dxte\\node_modules\\arduino-upload\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Ali\AppData\Local\Temp\apm-install-dir-117310-7644-1i0dxte\node_modules\arduino-upload\node_modules\serialport
node-pre-gyp ERR! node -v v4.4.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Ali\AppData\Local\Temp\apm-install-dir-117310-7644-1i0dxte\package.json'
npm WARN apm-install-dir-117310-7644-1i0dxte No description
npm WARN apm-install-dir-117310-7644-1i0dxte No repository field.
npm WARN apm-install-dir-117310-7644-1i0dxte No README data
npm WARN apm-install-dir-117310-7644-1i0dxte No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Ali\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Ali\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Ali\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Ali\\.atom\\.apmrc" "install" "C:\\Users\\Ali\\AppData\\Local\\Temp\\d-117310-7644-i2zdp2\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@4.0.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Ali\AppData\Local\Temp\apm-install-dir-117310-7644-1i0dxte\npm-debug.log
npm ERR! code 1

**Comment by Sorunome** [comment] 2017-04-10 19:49
Duplicate of #8

**Closed by Sorunome** 2017-04-10 19:49 UTC
