### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by angelodumitriu** [Sorunome/arduino-upload#22] opened 2017-05-17 07:24 UTC
I am facin an issue trying to install the plugin. This is the report file.

I have already tried to install Python 2.7 which seemed to work for some people, but I still can't install.

> Installing “arduino-upload@1.0.3” failed.Hide output…
> 
> > serialport@4.0.7 install C:\Users\ANGELO~1\AppData\Local\Temp\apm-install-dir-117417-8128-qsjo87.tkxbtymn29\node_modules\arduino-upload\node_modules\serialport
> > node-pre-gyp install --fallback-to-build
> 
> Compilazione dei progetti nella soluzione uno alla volta. Per abilitare la compilazione parallela, aggiungere l'opzione "/m".
> MSBUILD : error MSB3428: impossibile caricare il componente di Visual C++ "VCBuild.exe". Per risolvere il problema, 1) installare .NET Framework 2.0 SDK, 2) Microsoft Visual Studio 2005 oppure 3) aggiungere al percorso di sistema il percorso del componente se questo � installato altrove.  [C:\Users\ANGELO~1\AppData\Local\Temp\apm-install-dir-117417-8128-qsjo87.tkxbtymn29\node_modules\arduino-upload\node_modules\serialport\build\binding.sln]
> Failed to execute 'C:\Users\Angelo Dumitriu\AppData\Local\atom\app-1.17.0\resources\app\apm\bin\node.exe C:\Users\Angelo Dumitriu\AppData\Local\atom\app-1.17.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\ANGELO~1\AppData\Local\Temp\apm-install-dir-117417-8128-qsjo87.tkxbtymn29\node_modules\arduino-upload\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\ANGELO~1\AppData\Local\Temp\apm-install-dir-117417-8128-qsjo87.tkxbtymn29\node_modules\arduino-upload\node_modules\serialport\build\Release' (1)
> C:\Users\ANGELO~1\AppData\Local\Temp\apm-install-dir-117417-8128-qsjo87.tkxbtymn29
> `-- (empty)
> 
> 
> node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-electron-v1.3-win32-x64.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and electron@1.3.15 (electron-v1.3 ABI) (falling back to source compile with node-gyp) 
> gyp ERR! build error 
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\Angelo Dumitriu\AppData\Local\atom\app-1.17.0\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Windows_NT 6.3.9600
> gyp ERR! command "C:\\Users\\Angelo Dumitriu\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Angelo Dumitriu\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\ANGELO~1\\AppData\\Local\\Temp\\apm-install-dir-117417-8128-qsjo87.tkxbtymn29\\node_modules\\arduino-upload\\node_modules\\serialport\\build\\Release\\serialport.node" "--module_name=serialport" "--module_path=C:\\Users\\ANGELO~1\\AppData\\Local\\Temp\\apm-install-dir-117417-8128-qsjo87.tkxbtymn29\\node_modules\\arduino-upload\\node_modules\\serialport\\build\\Release"
> gyp ERR! cwd C:\Users\ANGELO~1\AppData\Local\Temp\apm-install-dir-117417-8128-qsjo87.tkxbtymn29\node_modules\arduino-upload\node_modules\serialport
> gyp ERR! node -v v6.9.5
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\Angelo Dumitriu\AppData\Local\atom\app-1.17.0\resources\app\apm\bin\node.exe C:\Users\Angelo Dumitriu\AppData\Local\atom\app-1.17.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\ANGELO~1\AppData\Local\Temp\apm-install-dir-117417-8128-qsjo87.tkxbtymn29\node_modules\arduino-upload\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\ANGELO~1\AppData\Local\Temp\apm-install-dir-117417-8128-qsjo87.tkxbtymn29\node_modules\arduino-upload\node_modules\serialport\build\Release' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\ANGELO~1\AppData\Local\Temp\apm-install-dir-117417-8128-qsjo87.tkxbtymn29\node_modules\arduino-upload\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
> node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> node-pre-gyp ERR! System Windows_NT 6.3.9600
> node-pre-gyp ERR! command "C:\\Users\\Angelo Dumitriu\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\ANGELO~1\\AppData\\Local\\Temp\\apm-install-dir-117417-8128-qsjo87.tkxbtymn29\\node_modules\\arduino-upload\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd C:\Users\ANGELO~1\AppData\Local\Temp\apm-install-dir-117417-8128-qsjo87.tkxbtymn29\node_modules\arduino-upload\node_modules\serialport
> node-pre-gyp ERR! node -v v6.9.5
> node-pre-gyp ERR! node-pre-gyp -v v0.6.32
> node-pre-gyp ERR! not ok 
> npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\ANGELO~1\AppData\Local\Temp\apm-install-dir-117417-8128-qsjo87.tkxbtymn29\package.json'
> npm WARN apm-install-dir-117417-8128-qsjo87.tkxbtymn29 No description
> npm WARN apm-install-dir-117417-8128-qsjo87.tkxbtymn29 No repository field.
> npm WARN apm-install-dir-117417-8128-qsjo87.tkxbtymn29 No README data
> npm WARN apm-install-dir-117417-8128-qsjo87.tkxbtymn29 No license field.
> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\\Users\\Angelo Dumitriu\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Angelo Dumitriu\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Angelo Dumitriu\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Angelo Dumitriu\\.atom\\.apmrc" "install" "C:\\Users\\ANGELO~1\\AppData\\Local\\Temp\\d-117417-8128-vw5w0b.zj31o9wwmi\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
> npm ERR! node v6.9.5
> npm ERR! npm  v3.10.5
> npm ERR! code ELIFECYCLE
> 
> npm ERR! serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the serialport@4.0.7 install script 'node-pre-gyp install --fallback-to-build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the serialport package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-pre-gyp install --fallback-to-build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs serialport
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls serialport
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\ANGELO~1\AppData\Local\Temp\apm-install-dir-117417-8128-qsjo87.tkxbtymn29\npm-debug.log
> npm ERR! code 1

**Comment by Sorunome** [comment] 2017-07-06 15:43
Duplicate of #19

**Closed by Sorunome** 2017-07-06 15:43 UTC
