### ISSUE TITLE
Select Arduino board and port manually [enhancement]

### ISSUE THREAD

**Issue by cfvescovo** [Sorunome/arduino-upload#45] opened 2018-06-22 14:24 UTC
I really like your plugin for Atom and I use it everyday but it would be even better if you added a board and port menu on the bottom bar.

**Comment by Sorunome** [comment] 2018-06-22 15:05
The board menu is at the bottom bar (it only shows up if you are in a source file of an arduino project) and the port is automatically determined, making the port menu obsolete

**Comment by StaticRocket** [comment] 2018-07-17 20:56
Duplicate of #36

**Comment by BaldEagleX02** [comment] 2018-07-18 20:29
@Sorunome If I have 2 Arduino connected to 2 USB ports it doesn't work.

**Closed as completed** 2018-11-02 03:21 UTC
