### ISSUE TITLE
Download is down

### ISSUE THREAD

**Issue by FlorianHill** [Sorunome/arduino-upload#23] opened 2017-06-04 17:31 UTC
Got always an error when installing arduino-upload.
`Installing “arduino-upload@1.0.3” failed.Hide output…

> serialport@4.0.7 install C:\Users\flori\AppData\Local\Temp\apm-install-dir-11754-10804-1c1qix1.atvsawnrk9\node_modules\arduino-upload\node_modules\serialport
> node-pre-gyp install --fallback-to-build

Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm�glichen, m�ssen Sie den Schalter "/m" hinzuf�gen.
MSBUILD : error MSB3428: Die Visual C++-Komponente "VCBuild.exe" konnte nicht geladen werden. Um dieses Problem zu beheben, installieren Sie entweder 1) .NET Framework 2.0 SDK oder 2) Microsoft Visual Studio 2005 oder 3) f�gen Sie den Speicherort der Komponente zum Systempfad hinzu, falls er vom Standardspeicherort abweicht.  [C:\Users\flori\AppData\Local\Temp\apm-install-dir-11754-10804-1c1qix1.atvsawnrk9\node_modules\arduino-upload\node_modules\serialport\build\binding.sln]
Failed to execute 'C:\Users\flori\AppData\Local\atom\app-1.17.2\resources\app\apm\bin\node.exe C:\Users\flori\AppData\Local\atom\app-1.17.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\flori\AppData\Local\Temp\apm-install-dir-11754-10804-1c1qix1.atvsawnrk9\node_modules\arduino-upload\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\flori\AppData\Local\Temp\apm-install-dir-11754-10804-1c1qix1.atvsawnrk9\node_modules\arduino-upload\node_modules\serialport\build\Release' (1)
C:\Users\flori\AppData\Local\Temp\apm-install-dir-11754-10804-1c1qix1.atvsawnrk9
`-- (empty)

node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-electron-v1.3-win32-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and electron@1.3.15 (electron-v1.3 ABI) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\flori\AppData\Local\atom\app-1.17.2\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\flori\\AppData\\Local\\atom\\app-1.17.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\flori\\AppData\\Local\\atom\\app-1.17.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\flori\\AppData\\Local\\Temp\\apm-install-dir-11754-10804-1c1qix1.atvsawnrk9\\node_modules\\arduino-upload\\node_modules\\serialport\\build\\Release\\serialport.node" "--module_name=serialport" "--module_path=C:\\Users\\flori\\AppData\\Local\\Temp\\apm-install-dir-11754-10804-1c1qix1.atvsawnrk9\\node_modules\\arduino-upload\\node_modules\\serialport\\build\\Release"
gyp ERR! cwd C:\Users\flori\AppData\Local\Temp\apm-install-dir-11754-10804-1c1qix1.atvsawnrk9\node_modules\arduino-upload\node_modules\serialport
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\flori\AppData\Local\atom\app-1.17.2\resources\app\apm\bin\node.exe C:\Users\flori\AppData\Local\atom\app-1.17.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\flori\AppData\Local\Temp\apm-install-dir-11754-10804-1c1qix1.atvsawnrk9\node_modules\arduino-upload\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\flori\AppData\Local\Temp\apm-install-dir-11754-10804-1c1qix1.atvsawnrk9\node_modules\arduino-upload\node_modules\serialport\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\flori\AppData\Local\Temp\apm-install-dir-11754-10804-1c1qix1.atvsawnrk9\node_modules\arduino-upload\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Users\\flori\\AppData\\Local\\atom\\app-1.17.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\flori\\AppData\\Local\\Temp\\apm-install-dir-11754-10804-1c1qix1.atvsawnrk9\\node_modules\\arduino-upload\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\flori\AppData\Local\Temp\apm-install-dir-11754-10804-1c1qix1.atvsawnrk9\node_modules\arduino-upload\node_modules\serialport
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\flori\AppData\Local\Temp\apm-install-dir-11754-10804-1c1qix1.atvsawnrk9\package.json'
npm WARN apm-install-dir-11754-10804-1c1qix1.atvsawnrk9 No description
npm WARN apm-install-dir-11754-10804-1c1qix1.atvsawnrk9 No repository field.
npm WARN apm-install-dir-11754-10804-1c1qix1.atvsawnrk9 No README data
npm WARN apm-install-dir-11754-10804-1c1qix1.atvsawnrk9 No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\flori\\AppData\\Local\\atom\\app-1.17.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\flori\\AppData\\Local\\atom\\app-1.17.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\flori\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\flori\\.atom\\.apmrc" "install" "C:\\Users\\flori\\AppData\\Local\\Temp\\d-11754-10804-1sv5zj.9m3ip8ehfr\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@4.0.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\flori\AppData\Local\Temp\apm-install-dir-11754-10804-1c1qix1.atvsawnrk9\npm-debug.log
npm ERR! code 1
`
When trying to open the URL, you got an Github 404 :P 

[https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-electron-v1.3-win32-x64.tar.gz](https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-electron-v1.3-win32-x64.tar.gz )

**Comment by Sorunome** [comment] 2017-07-06 15:40
This is basically a duplicate of #8 and is only effecting windows, i have literetally no idea how to fix it :(

At least in the version I just published I have fallback to some simpler version (such people will lack serialmonitor and auto-detection of arduino, so the serial port must still be set via the IDE once :/ )

**Closed by Sorunome** 2017-07-06 15:40 UTC
